#page title
page_title                                : "TranslateKit: App Localizer"                                          # Automatically populates with app name if not set and if App ID is set. Otherwise enter manually.

# App Info
app_id                                    : 6475053426                                # Required. Enter App ID to automatically populate name, price and icons (e.g. 718043190).
app_country                               : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
is_mac_app                                : true                                      # Required.

appstore_link                             : https://apps.apple.com/app/apple-store/id6476773066?pt=549314&ct=sctranslator.app&mt=8                                          # Automatically populates if not set and if App ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if App ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "TranslateKit: App Localizer"                                          # Automatically populates if not set and if App ID is set.  Otherwise enter manually.
app_price                                 : "10 languages & 200 strings free â€“ just $5/month for more"                                  # Automatically populates if not set and if App ID is set.  Otherwise enter manually.
app_description                           : Localize your XCStrings files!

enable_smart_app_banner                   : false                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cihat GÃ¼ndÃ¼z
your_link                                 : https://fline.dev/about/?ref=translatekit.app
your_city                                 : the EU ðŸ‡ªðŸ‡º
email_address                             : translatekit@fline.dev
facebook_username                         :
instagram_username                        :
twitter_username                          : 
mastodon_url                              : 
github_username                           : Jeehut
youtube_username                          : FlineDev
twitch_username                           : Jeehut



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Drag & Drop Simplicity
    description                           : Easily translate String Catalog (.xcstrings) files with a simple drag-and-drop action.
    fontawesome_icon_name                 : mouse-pointer
    gif_name                              : 

  - title                                 : Multi-Service & Language Support
    description                           : Access translations in over 150 languages from Google, Microsoft, DeepL, Yandex.
    fontawesome_icon_name                 : language
    gif_name                              : 

  - title                                 : Automatic Empty Field Detection
    description                           : Smart detection and translation only of empty fields in your String Catalog files.
    fontawesome_icon_name                 : binoculars
    gif_name                              : AppPreview

  - title                                 : Built-In Common Translations
    description                           : Over 1,500 confirmed translations ensure common texts like 'Save' are correctly translated.
    fontawesome_icon_name                 : book
    gif_name                              :

  - title                                 : Consistency with Apple Terminology
    description                           : Use the menu bar extra to search for common translations and copy them without leaving Xcode.
    fontawesome_icon_name                 : apple
    gif_name                              :

  - title                                 : Built-In Translation Editor
    description                           : Use our String Catalog editor as it supports more features than Xcode, such as batch-review.
    fontawesome_icon_name                 : edit
    gif_name                              : TranslationEditor

  - title                                 : Parameter Mismatch Detection
    description                           : Find bugs in your translations with built-in checks for missing parameters in other languages.
    fontawesome_icon_name                 : exclamationmark-triangle
    gif_name                              :

  - title                                 : Great Accuracy
    description                           : Achieve accurate, context-aware translations with top-tier services.
    fontawesome_icon_name                 : check-circle
    gif_name                              : 

  - title                                 : Boost Productivity
    description                           : Focus on development while the app handles localization.
    fontawesome_icon_name                 : rocket
    gif_name                              : 

  - title                                 : Global Reach
    description                           : Expand your app's audience worldwide with minimal effort.
    fontawesome_icon_name                 : globe
    gif_name                              : 


# Theme Settings
topbar_color                              : "#042745"
topbar_transparency                       : 0.35
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#063257"
cover_overlay_transparency                : 0.77

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
