#page title
page_title                                :                                           # Automatically populates with app name if not set and if App ID is set. Otherwise enter manually.

# App Info
app_id                                    : 1605635026                                # Required. Enter App ID to automatically populate name, price and icons (e.g. 718043190).
app_country                               : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
is_mac_app                                : true                                      # Required.

appstore_link                             : https://apps.apple.com/app/apple-store/id1605635026?pt=549314&ct=remafox.app&mt=8                                          # Automatically populates if not set and if App ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://github.com/FlineDev/RemafoX-LandingPage/raw/main/downloads/PressKit-v1.5.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if App ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if App ID is set.  Otherwise enter manually.
app_price                                 : "Freemium (Free: 200 texts & 10 languages per project)"                                  # Automatically populates if not set and if App ID is set.  Otherwise enter manually.
app_description                           : Reduce the developers' app translation time by 90%!

enable_smart_app_banner                   : false                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cihat GÃ¼ndÃ¼z
your_link                                 : https://fline.dev/about/
your_city                                 : the EU ðŸ‡ªðŸ‡º
email_address                             : support@fline.dev
facebook_username                         :
instagram_username                        :
twitter_username                          : RemafoX_App
github_username                           : FlineDev/RemafoX
youtube_username                          : FlineDev
twitch_username                           : Jeehut



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Reduce Number of Steps
    description                           : No longer manually edit Strings in different languages when adding new keys.
    fontawesome_icon_name                 : stopwatch
    gif_name                             : 

  - title                                 : Reduce Context Switches
    description                           : Don't even leave the context of your Swift file â€“ stay focused.
    fontawesome_icon_name                 : smile
    gif_name                             : 

  - title                                 : Pluralization made easy
    description                           : Full support for pluralization via Stringsdict files without the need to learn about their syntax.
    fontawesome_icon_name                 : th-list
    gif_name                             : AddTranslation

  - title                                 : Machine Translation
    description                           : Setup your DeepL or Microsoft Translator API keys and machine translate your entire app.
    fontawesome_icon_name                 : robot
    gif_name                             : 

  - title                                 : Linter
    description                           : Get warnings for translation issues such as empty translations or duplicate keys.
    fontawesome_icon_name                 : check-circle
    gif_name                             : 

  - title                                 : Normalizer
    description                           : Find translations faster in your Strings files by sorting their keys alphabetically.
    fontawesome_icon_name                 : broom
    gif_name                             : LintMachineTranslate

  - title                                 : Smart machine translation
    description                           : Translating pluralized texts is made easy by an automatic language-aware mapping of plural cases.
    fontawesome_icon_name                 : brain
    gif_name                             : 

  - title                                 : Storyboard/XIB Synchronizer
    description                           : Automatically update the Strings files of localized Interface Builder files on changes.
    fontawesome_icon_name                 : sync
    gif_name                             : 

  - title                                 : Beginner-friendly
    description                           : Lots of expandable explanations, step-by-step guides and even video guides available.
    fontawesome_icon_name                 : graduation-cap
    gif_name                             : ProjectSetup

  - title                                 : Flexible Payment
    description                           : Advanced features are available via both subscriptions and one-time purchases.
    fontawesome_icon_name                 : store
    gif_name                             : 

  - title                                 : Regular Updates
    description                           : This is just the beginning. With monthly feature updates, more things are on the horizon.
    fontawesome_icon_name                 : arrow-up
    gif_name                             : 

  - title                                 : Free Tier
    description                           : For smaller projects, most features are fully available. Open Source project get all features for free!
    fontawesome_icon_name                 : coins
    gif_name                             : 



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.33

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
