#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1605635026                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/remafox-easy-app-localization/id1605635026                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Improved Xcode translation workflow.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cihat Gündüz
your_link                                 : https://twitter.com/Jeehut
your_city                                 : Europe
email_address                             : support@fline.dev
facebook_username                         :
instagram_username                        :
twitter_username                          : ReMafoX_App
github_username                           : FlineDev
youtube_username                          : FlineDev
twitch_username                           : Jeehut



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Reduce Number of Steps
    description                           : No longer manually edit Strings in different languages when adding new keys.
    fontawesome_icon_name                 : stopwatch

  - title                                 : Reduce Context Switches
    description                           : Don't even leave the context of your Swift file – stay focused.
    fontawesome_icon_name                 : smile

  - title                                 : Machine Translation
    description                           : Setup your DeepL or Microsoft Translator API keys and machine translate your entire app.
    fontawesome_icon_name                 : robot

  - title                                 : Linter
    description                           : Get warnings for translation issues such as empty translations or duplicate keys.
    fontawesome_icon_name                 : check-circle

  - title                                 : Normalizer
    description                           : Find translations faster in your Strings files by sorting their keys alphabetically.
    fontawesome_icon_name                 : broom

  - title                                 : Storyboard/XIB Synchronizer
    description                           : Automatically update the Strings files of localized Interface Builder files on changes.
    fontawesome_icon_name                 : sync

  - title                                 : Beginner-friendly
    description                           : Lots of expandable explanations, step-by-step guides and even video guides available.
    fontawesome_icon_name                 : graduation-cap

  - title                                 : Pluralization made easy
    description                           : Full support for pluralization via Stringsdict files without the need to learn about their syntax.
    fontawesome_icon_name                 : th-list

  - title                                 : Smart machine translation
    description                           : Translating pluralized texts is made easy by an automatic language-aware mapping of plural cases.
    fontawesome_icon_name                 : brain

  - title                                 : Flexible Payment
    description                           : Advanced features are available via both subscriptions and one-time purchases.
    fontawesome_icon_name                 : store

  - title                                 : Regular Updates
    description                           : This is just the beginning. With monthly feature updates, more things are on the horizon.
    fontawesome_icon_name                 : sparkles

  - title                                 : Free Tier
    description                           : For smaller projects, most of the features are fully available without the need to pay anything.
    fontawesome_icon_name                 : coins



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
